"""add claude_api_key_encrypted to users

Revision ID: c1d5350bb61a
Revises: 60aac514bec4
Create Date: 2026-02-23 11:36:25.726870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d5350bb61a'
down_revision = '60aac514bec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claude_api_key_encrypted', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('claude_api_key_encrypted')

    # ### end Alembic commands ###
